lists/urls.py
from django.urls import path

from . import views
from ratings.views import rate_movie_view

app_name = 'list'

urlpatterns = [
    path('', views.movie_list_view, name='index'),
    path('create', views.add_movie_to_list_view, name='add_movie'),
    path('<int:movie_id>/delete',
         views.delete_movie_from_list_view, name='delete_movie'),
    path('<int:movie_id>/vote', rate_movie_view, name='rate_movie')
]

movieSiteDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', home_page, name='home'),
    path('movies/', include('movies.urls')),
    path('list/', include('lists.urls'))
]

lists/models.py
# pylint: disable=E1101
from django.db import models
from django.conf import settings

from movies.models import Movie
from ratings.models import UserRating


class List(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie_list = models.ManyToManyField(Movie, default=None)

    # objects = MovieListManager()

    def __str__(self):
        return f'{self.user.username} list'

    def get_user_movies(self):
        return self.movie_list.all()

    def movie_in_list(self, movie):
        return movie in self.movie_list.all()

    def add_movie_to_list(self, movie):
        new_movie = Movie.objects.get_or_create(movie)
        self.movie_list.add(new_movie)

    def remove_movie_from_list(self, movie):
        self.movie_list.remove(movie)

lists/forms.py
from django import forms

class MovieForm(forms.Form):
    title = forms.CharField()
    poster = forms.CharField()
    year = forms.IntegerField()

lists/views.py
# pylint: disable=E1101
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from rest_framework import status, permissions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.parsers import JSONParser

from movies.serializers import UserMovieSerializer, MovieSerializer
from .models import List
from movies.models import Movie
from .forms import MovieForm
from .utils import format_movie

from django.contrib.auth.models import User

# @login_required
# def movie_list_view(request):
#     user = request.user
#     user_movies = user.list.get_user_movies()
#     for movie in user_movies:
#         movie.user_rating = movie.get_user_rating(user)
#     context = {'movies': user_movies}
#     return render(request, 'lists/list.html', context)


def add_ratings_to_movie(movie, user=None):
    movie.movie_rating = movie.get_movie_rating()
    if user is not None:
        movie.user_rating = movie.get_user_rating(user)

@api_view(['GET'])
@permission_classes((permissions.IsAuthenticated,))
def movie_list_view(request):
    user = request.user
    user_movies = user.list.get_user_movies()
    for movie in user_movies:
        add_ratings_to_movie(movie, user)
    serializer = UserMovieSerializer(user_movies, many=True)
    return Response(serializer.data)


# @login_required
# def add_movie_to_list_view(request):
#     form = MovieForm(request.POST or None)
#     context = {'form': form}
#     if form.is_valid():
#         new_movie = format_movie(request.POST)
#         user_list = request.user.list
#         user_list.add_movie_to_list(new_movie)
#         return redirect('list:index')
#     return render(request, 'lists/add_movie.html', context)


@csrf_exempt
@permission_classes((permissions.IsAuthenticated,))
@api_view(['POST'])
def add_movie_to_list_view(request):
    new_movie = Movie(**request.data)
    user_list = request.user.list
    user_list.add_movie_to_list(new_movie)
    add_ratings_to_movie(new_movie)
    serializer = MovieSerializer(new_movie)
    return Response(serializer.data, status=status.HTTP_201_CREATED)


# def delete_movie_from_list_view(request, movie_id):
#     user_list = request.user.list
#     movie = get_object_or_404(Movie, pk=movie_id)
#     if user_list.movie_in_list(movie):
#         user_list.remove_movie_from_list(movie)
#         return redirect('list:index')
#     return redirect('list:index')

@permission_classes((permissions.IsAuthenticated,))
@api_view(['POST'])
def delete_movie_from_list_view(request, movie_id):
    user_list = request.user.list
    movie = get_object_or_404(Movie, pk=movie_id)
    if user_list.movie_in_list(movie):
        user_list.remove_movie_from_list(movie)
        return Response(status=status.HTTP_204_NO_CONTENT)
        # return HttpResponse("movie removed")
    return Response(status=status.HTTP_404_NOT_FOUND)

lists/templates/lists/add_movie.html
<h1>Add movie</h1>

<form action="{% url 'list:add_movie' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>

lists/templates/lists/list.html
<style>
    li {
        display: flex;
    }

</style>

<h1>Movie list</h1>

<ul>
    {% for movie in movies %}
        <li>
            {{ movie.rating.rating }}
            {{ movie.title }} --
            <form action="{% url 'list:rate_movie' movie.id %}" method="post">
                {% csrf_token %}
                <select name="user-rating">
                    <option value="1" {% if movie.user_rating is 1 %} selected {% endif %}>1</option>
                    <option value="2" {% if movie.user_rating is 2 %} selected {% endif %}>2</option>
                    <option value="3" {% if movie.user_rating is 3 %} selected {% endif %}>3</option>
                    <option value="4" {% if movie.user_rating is 4 %} selected {% endif %}>4</option>
                    <option value="5" {% if movie.user_rating is 5 %} selected {% endif %}>5</option>
                    <input type="submit" value="Vote">
                </select>
            </form>
            {% include 'lists/snippets/delete.html' %}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'list:add_movie' %}">Add Movie</a>